version: '3'

services:
  Sun-Biosystems:
    image: localhost:56156/Sun-Biosystems
    build:
      context: ../../../ # do not change
      dockerfile: Challenges/Miscellanious/Sun-Biosystems/Dockerfile
    networks:
      nw0:
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.1'

networks:
  nw0:
    external: true